/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import styles from "./MyComponent.module.css";

export default function MyComponent() {
  return (
    <>
      <a href="https://kredsmart.ai" target="_blank" className={styles.a}>
        <div className={styles.navBar}>
          <div className={styles.logo}>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/d1843da584bc9c5a321bc316ea1fae3b594024d111db98dc390c1a0e6510dee5?apiKey=2ea34b46751a4a27af43fd1d1256e872&"
              className={styles.img}
            />
            <div className={styles.kredSmart}>KredSmart</div>
          </div>
          <div className={styles.navItems}>
            <div className={styles.navItem1}></div>
            <div className={styles.navItem2}>Our Features</div>
            <div className={styles.navItem3}></div>
          </div>
          <div className={styles.navItem32}></div>
        </div>
        <div className={styles.div} />
        <div className={styles.smartSavingsStartWithSmartSpendings}>
          Smart{" "}
          <span className = {styles.style1}>
            Savings
          </span>{" "}
          start with Smart{" "}
          <span className = {styles.style1}>
            Spendings
          </span>
        </div>
        <div className={styles.analyzeAdoptSave}>
          Analyze<span className = {styles.style2}>.</span> Adopt
          <span className = {styles.style2}>.</span> Save
          <span className = {styles.style2}>.</span>
        </div>
        <img
          loading="lazy"
          srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/e5bc4f1d7454d80f5a2404b70abc62e6c7a25b63a87354aa4aa3dbf043e4c344?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/e5bc4f1d7454d80f5a2404b70abc62e6c7a25b63a87354aa4aa3dbf043e4c344?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/e5bc4f1d7454d80f5a2404b70abc62e6c7a25b63a87354aa4aa3dbf043e4c344?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/e5bc4f1d7454d80f5a2404b70abc62e6c7a25b63a87354aa4aa3dbf043e4c344?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/e5bc4f1d7454d80f5a2404b70abc62e6c7a25b63a87354aa4aa3dbf043e4c344?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/e5bc4f1d7454d80f5a2404b70abc62e6c7a25b63a87354aa4aa3dbf043e4c344?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/e5bc4f1d7454d80f5a2404b70abc62e6c7a25b63a87354aa4aa3dbf043e4c344?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/e5bc4f1d7454d80f5a2404b70abc62e6c7a25b63a87354aa4aa3dbf043e4c344?apiKey=2ea34b46751a4a27af43fd1d1256e872&"
          className={styles.img2}
        />
        <div className={styles.div2}>
          <div className={styles.div3}>
            <div className={styles.column}>
              <div className={styles.div4}>
                <div className={styles.div5}>
                  <div className={styles.column2}>
                    <div className={styles.div6}>
                      <div className={styles.div7}>
                        <div className={styles.div8}>
                          <div
                            className={styles.trackYourSpendsCompareToYourPeers}
                          >
                            Track your spends & compare to your peers
                          </div>
                          <div
                            className={
                              styles.getADetailedAnalysisOfYourSpendingsAndSeeHowPeopleSimilarToYouSpent
                            }
                          >
                            Get a detailed{" "}
                            <span className="styles.style3">
                              analysis
                            </span>{" "}
                            of your spendings and see how{" "}
                            <span className="styles.style3">
                              people similar to you
                            </span>{" "}
                            spent.
                          </div>
                        </div>
                      </div>
                      <img
                        loading="lazy"
                        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/016246b33a96edb9e571ff8dc3b5e93fd600f9af41a3dfbce2abc79530dd15f6?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/016246b33a96edb9e571ff8dc3b5e93fd600f9af41a3dfbce2abc79530dd15f6?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/016246b33a96edb9e571ff8dc3b5e93fd600f9af41a3dfbce2abc79530dd15f6?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/016246b33a96edb9e571ff8dc3b5e93fd600f9af41a3dfbce2abc79530dd15f6?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/016246b33a96edb9e571ff8dc3b5e93fd600f9af41a3dfbce2abc79530dd15f6?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/016246b33a96edb9e571ff8dc3b5e93fd600f9af41a3dfbce2abc79530dd15f6?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/016246b33a96edb9e571ff8dc3b5e93fd600f9af41a3dfbce2abc79530dd15f6?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/016246b33a96edb9e571ff8dc3b5e93fd600f9af41a3dfbce2abc79530dd15f6?apiKey=2ea34b46751a4a27af43fd1d1256e872&"
                        className={styles.img3}
                      />
                    </div>
                  </div>
                  <div className={styles.column3}>
                    <img
                      loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/40cdcd1c5569af3f827dbf5956e7bb5060f988a1f7bb1ba5cc128dc065cb1afb?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/40cdcd1c5569af3f827dbf5956e7bb5060f988a1f7bb1ba5cc128dc065cb1afb?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/40cdcd1c5569af3f827dbf5956e7bb5060f988a1f7bb1ba5cc128dc065cb1afb?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/40cdcd1c5569af3f827dbf5956e7bb5060f988a1f7bb1ba5cc128dc065cb1afb?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/40cdcd1c5569af3f827dbf5956e7bb5060f988a1f7bb1ba5cc128dc065cb1afb?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/40cdcd1c5569af3f827dbf5956e7bb5060f988a1f7bb1ba5cc128dc065cb1afb?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/40cdcd1c5569af3f827dbf5956e7bb5060f988a1f7bb1ba5cc128dc065cb1afb?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/40cdcd1c5569af3f827dbf5956e7bb5060f988a1f7bb1ba5cc128dc065cb1afb?apiKey=2ea34b46751a4a27af43fd1d1256e872&"
                      className={styles.img4}
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className={styles.column4}>
              <img
                loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/938091ed7fb75ddb4eeb030a630250a15700e7679bdd83954a288986836d53f7?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/938091ed7fb75ddb4eeb030a630250a15700e7679bdd83954a288986836d53f7?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/938091ed7fb75ddb4eeb030a630250a15700e7679bdd83954a288986836d53f7?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/938091ed7fb75ddb4eeb030a630250a15700e7679bdd83954a288986836d53f7?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/938091ed7fb75ddb4eeb030a630250a15700e7679bdd83954a288986836d53f7?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/938091ed7fb75ddb4eeb030a630250a15700e7679bdd83954a288986836d53f7?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/938091ed7fb75ddb4eeb030a630250a15700e7679bdd83954a288986836d53f7?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/938091ed7fb75ddb4eeb030a630250a15700e7679bdd83954a288986836d53f7?apiKey=2ea34b46751a4a27af43fd1d1256e872&"
                className={styles.img5}
              />
            </div>
          </div>
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/3c927d5b4b6bd998b24649814d1d4e7b647e411f0178ac9a035dfc32fe940787?apiKey=2ea34b46751a4a27af43fd1d1256e872&"
          className={styles.img6}
        />
        <div className={styles.div9}>
          <div className={styles.div10}>
            <div className={styles.column5}>
              <div className={styles.div11}>
                <div className={styles.div12}>
                  <div className={styles.column6}>
                    <div className={styles.div13}>
                      <div className={styles.div14}>
                        <div className={styles.div15}>
                          <div className={styles.creditCardRecommendation}>
                            Credit card recommendation
                          </div>
                          <div
                            className={
                              styles.getMaximumSavingsByFindingTheRightCreditCardThatSuitsYourNeeds
                            }
                          >
                            Get maximum savings by finding the{" "}
                            <span className="styles.style4">
                              right credit card
                            </span>{" "}
                            that suits your needs.
                          </div>
                        </div>
                      </div>
                      <img
                        loading="lazy"
                        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/1165b7cf56fa7523ec7aebb03d94dc9eb0202602a630e89ef7711f3f427c80b3?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/1165b7cf56fa7523ec7aebb03d94dc9eb0202602a630e89ef7711f3f427c80b3?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/1165b7cf56fa7523ec7aebb03d94dc9eb0202602a630e89ef7711f3f427c80b3?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/1165b7cf56fa7523ec7aebb03d94dc9eb0202602a630e89ef7711f3f427c80b3?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/1165b7cf56fa7523ec7aebb03d94dc9eb0202602a630e89ef7711f3f427c80b3?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/1165b7cf56fa7523ec7aebb03d94dc9eb0202602a630e89ef7711f3f427c80b3?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/1165b7cf56fa7523ec7aebb03d94dc9eb0202602a630e89ef7711f3f427c80b3?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/1165b7cf56fa7523ec7aebb03d94dc9eb0202602a630e89ef7711f3f427c80b3?apiKey=2ea34b46751a4a27af43fd1d1256e872&"
                        className={styles.img7}
                      />
                    </div>
                  </div>
                  <div className={styles.column7}>
                    <img
                      loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/0bd4c08f0c19ccc63e590fcef322106bf77ef370b2a18146f3073a1da9dee1ce?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/0bd4c08f0c19ccc63e590fcef322106bf77ef370b2a18146f3073a1da9dee1ce?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0bd4c08f0c19ccc63e590fcef322106bf77ef370b2a18146f3073a1da9dee1ce?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/0bd4c08f0c19ccc63e590fcef322106bf77ef370b2a18146f3073a1da9dee1ce?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/0bd4c08f0c19ccc63e590fcef322106bf77ef370b2a18146f3073a1da9dee1ce?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0bd4c08f0c19ccc63e590fcef322106bf77ef370b2a18146f3073a1da9dee1ce?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/0bd4c08f0c19ccc63e590fcef322106bf77ef370b2a18146f3073a1da9dee1ce?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/0bd4c08f0c19ccc63e590fcef322106bf77ef370b2a18146f3073a1da9dee1ce?apiKey=2ea34b46751a4a27af43fd1d1256e872&"
                      className={styles.img8}
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className={styles.column8}>
              <img
                loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/ef0713fb3d6c81ec3b472b64cb5d32118ac7a6600c9dbafcc5dd5cb54bdc3973?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/ef0713fb3d6c81ec3b472b64cb5d32118ac7a6600c9dbafcc5dd5cb54bdc3973?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ef0713fb3d6c81ec3b472b64cb5d32118ac7a6600c9dbafcc5dd5cb54bdc3973?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/ef0713fb3d6c81ec3b472b64cb5d32118ac7a6600c9dbafcc5dd5cb54bdc3973?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/ef0713fb3d6c81ec3b472b64cb5d32118ac7a6600c9dbafcc5dd5cb54bdc3973?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ef0713fb3d6c81ec3b472b64cb5d32118ac7a6600c9dbafcc5dd5cb54bdc3973?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/ef0713fb3d6c81ec3b472b64cb5d32118ac7a6600c9dbafcc5dd5cb54bdc3973?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/ef0713fb3d6c81ec3b472b64cb5d32118ac7a6600c9dbafcc5dd5cb54bdc3973?apiKey=2ea34b46751a4a27af43fd1d1256e872&"
                className={styles.img9}
              />
            </div>
          </div>
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/3c927d5b4b6bd998b24649814d1d4e7b647e411f0178ac9a035dfc32fe940787?apiKey=2ea34b46751a4a27af43fd1d1256e872&"
          className={styles.img10}
        />
        <div className={styles.div16}>
          <div className={styles.div17}>
            <div className={styles.column9}>
              <div className={styles.div18}>
                <div className={styles.div19}>
                  <div className={styles.column10}>
                    <img
                      loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/9eb785b78e3a3dac44be7501a133413d07031f5f0c572520aded8d99bc28c340?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/9eb785b78e3a3dac44be7501a133413d07031f5f0c572520aded8d99bc28c340?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/9eb785b78e3a3dac44be7501a133413d07031f5f0c572520aded8d99bc28c340?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/9eb785b78e3a3dac44be7501a133413d07031f5f0c572520aded8d99bc28c340?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/9eb785b78e3a3dac44be7501a133413d07031f5f0c572520aded8d99bc28c340?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/9eb785b78e3a3dac44be7501a133413d07031f5f0c572520aded8d99bc28c340?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/9eb785b78e3a3dac44be7501a133413d07031f5f0c572520aded8d99bc28c340?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/9eb785b78e3a3dac44be7501a133413d07031f5f0c572520aded8d99bc28c340?apiKey=2ea34b46751a4a27af43fd1d1256e872&"
                      className={styles.img11}
                    />
                  </div>
                  <div className={styles.column11}>
                    <div className={styles.div20}>
                      <div className={styles.div21}>
                        <div className={styles.column12}>
                          <div className={styles.div22}>
                            <div className={styles.div23}>
                              <div
                                className={styles.allSubscriptionsAtOnePlace}
                              >
                                All subscriptions at one place
                              </div>
                              <div
                                className={
                                  styles.manageIdentifyWhatYouSubscribeToAndTakeControlOfYourRepeatingExpenses
                                }
                              >
                                Manage & identify what you subscribe to and take
                                control of your{" "}
                                <span className="styles.style5">
                                  repeating expenses
                                </span>
                                !
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className={styles.column13}>
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/ebd8d8a9bfb8b2568cfc3f108af100a759c2c5f91ece53dc219c44c94d5736ff?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/ebd8d8a9bfb8b2568cfc3f108af100a759c2c5f91ece53dc219c44c94d5736ff?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ebd8d8a9bfb8b2568cfc3f108af100a759c2c5f91ece53dc219c44c94d5736ff?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/ebd8d8a9bfb8b2568cfc3f108af100a759c2c5f91ece53dc219c44c94d5736ff?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/ebd8d8a9bfb8b2568cfc3f108af100a759c2c5f91ece53dc219c44c94d5736ff?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ebd8d8a9bfb8b2568cfc3f108af100a759c2c5f91ece53dc219c44c94d5736ff?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/ebd8d8a9bfb8b2568cfc3f108af100a759c2c5f91ece53dc219c44c94d5736ff?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/ebd8d8a9bfb8b2568cfc3f108af100a759c2c5f91ece53dc219c44c94d5736ff?apiKey=2ea34b46751a4a27af43fd1d1256e872&"
                            className={styles.img12}
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className={styles.column14}>
              <img
                loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/aecc3e451cedb317511dc651066393c757d0e63869dee392a32d072242398141?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/aecc3e451cedb317511dc651066393c757d0e63869dee392a32d072242398141?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/aecc3e451cedb317511dc651066393c757d0e63869dee392a32d072242398141?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/aecc3e451cedb317511dc651066393c757d0e63869dee392a32d072242398141?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/aecc3e451cedb317511dc651066393c757d0e63869dee392a32d072242398141?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/aecc3e451cedb317511dc651066393c757d0e63869dee392a32d072242398141?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/aecc3e451cedb317511dc651066393c757d0e63869dee392a32d072242398141?apiKey=2ea34b46751a4a27af43fd1d1256e872&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/aecc3e451cedb317511dc651066393c757d0e63869dee392a32d072242398141?apiKey=2ea34b46751a4a27af43fd1d1256e872&"
                className={styles.img13}
              />
            </div>
          </div>
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/3c927d5b4b6bd998b24649814d1d4e7b647e411f0178ac9a035dfc32fe940787?apiKey=2ea34b46751a4a27af43fd1d1256e872&"
          className={styles.img14}
        />
      </a>
    </>
  );
}
